---
- hosts: all

  become: true

  vars_prompt:

    - name: "Adminpass"
      prompt: "Enter Admin password"
      private: no

    - name: "Databasepass"
      prompt: "Enter Database password"
      private: no

    - name: "Rabbitpass"
      prompt: "Enter Rabbit password"
      private: no


  tasks:

    - include: open.yml

